name: Propify-Solutions-Web

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js (Latest LTS)
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install PHP dependencies
        run: composer install --ignore-platform-reqs --no-interaction --prefer-dist

      - name: Install NPM dependencies
        run: npm install

      - name: Build Laravel + SSR
        run: npm run build
        env:
          VITE_TURNSTILE_SITE_KEY: ${{ secrets.VITE_TURNSTILE_SITE_KEY }}

      - name: Upload build + SSR files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: public/build/*,bootstrap/ssr/*
          target: /var/www/agency/PropifySolutionsLtd/

      - name: Run server-side deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/agency/PropifySolutionsLtd/
            git checkout -f
            git pull origin main
            composer install --ignore-platform-reqs --no-interaction --prefer-dist
            php artisan migrate --force --seed
            php artisan inertia:stop-ssr
            php artisan optimize:clear
            php artisan optimize
